// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Dummy URL for `prisma generate` at build time when DATABASE_URL is unset.
    url: process.env["DATABASE_URL"] ?? "postgresql://localhost:5432/dummy",
  },
});
